module.exports = {
  "agentName": "Infrastructure",
  "agentVersion": "1.19.1",
  "awsRegion": "us-east-1",
  "coreCount": "2",
  "entity.guid.INFRA": "MjQwMzUxNnxJTkZSQXxOQXwxODU3Mjg4NDczODAxOTg3NjY3",
  "entity.guids": "MjQwMzUxNnxJTkZSQXxOQXwxODU3Mjg4NDczODAxOTg3NjY3",
  "fb.input": "tail",
  "filePath": "/home/ubuntu/logginator/destination/access.log",
  "fullHostname": "ip-10-146-79-93.ec2.internal",
  "hostname": "ip-10-146-79-93",
  "instanceType": "t2.large",
  "kernelVersion": "5.4.0-1045-aws",
  "linuxDistribution": "Ubuntu 18.04.5 LTS",
  "operatingSystem": "linux",
  "plugin.source": "BARE-METAL",
  "plugin.type": "nri-agent",
  "plugin.version": "1.4.3",
  "processorCount": "2",
  "systemMemoryBytes": "8346386432",
}
